### ISSUE TITLE
Encode variable length types in lexicographic sort ordering

### ISSUE THREAD

**Issue by amirouche** [danburkert/bytekey#1]
Héllo,

I'm working on porting your library to GNU Guile, if I end up using your code you will be obviously cited for your work (I will attribute the bugs to myself :8ball:).

So my question is the following is the lexicographic order the same for `i64` and floats? If no, is it possible to come up with an algorithm that keeps all numbers (float or int) ordered. Also guile doesn't have limitations on the size of numbers do you think it's possible to build an algorithm that is limitless..?

I understand that this is a bit outside of the scope of bytekey, hopefully you have time to answer my questions.

**Comment by danburkert** [comment]
> I'm working on porting your library to GNU Guile

Cool! Let me know if you have any questions about the code.

> you will be obviously cited for your work

I didn't develop the algorithms in this library, so no need to attribute to me.  When developing this, I looked at [ndimiduk/orderly](https://github.com/ndimiduk/orderly) (a version of which was eventually pulled into HBase proper), and [sqlite](https://sqlite.org/src4/doc/trunk/www/key_encoding.wiki).

> So my question is the following is the lexicographic order the same for i64 and floats? If no, is it possible to come up with an algorithm that keeps all numbers (float or int) ordered.

I believe it is not in this implementation.  I think the sqlite version does correctly preserve ordering between floats and ints, but it has been a while since I looked at it.  I don't remember why I decided not to implement the library that way (probably performance or encoding size, and I don't have a need to compare across types).

> Also guile doesn't have limitations on the size of numbers do you think it's possible to build an algorithm that is limitless..?

Interesting question.  It is possible (although not yet implemented in this library) to encode variable length types in lexicographic sort ordering, usually by using a delimiter byte (and properly escaping the delimiter if it appears in the encoded value).  Maybe this method could be used to encode variable length ints?

**Comment by amirouche** [comment]
GNU Guile (and many other Scheme implementations) have bigints but not bigfloats.

I do not think it is possible to pack float and int while preserving their lexicographic order.

FWIW, I ported the foundationdb python bindings tuple packing functions.

Thanks!
